services:
  # ðŸŸ¢ Microservicio de CatÃ¡logo
  ms-catalogo:
    build: ./ms-catalogo
    container_name: ms-catalogo
    ports:
      - "5001:5001"
    restart: always

  # ðŸ”µ Microservicio de Pagos
  ms-pagos:
    build: ./ms-pagos
    container_name: ms-pagos
    ports:
      - "5002:5002"
    restart: always

  # ðŸŸ¡ Microservicio de Compras
  ms-compras:
    build: ./ms-compras
    container_name: ms-compras
    ports:
      - "5003:5003"
    restart: always
    depends_on:
      - ms-catalogo
      - ms-pagos
      - ms-inventario

  # ðŸŸ£ Microservicio de Inventario
  ms-inventario:
    build: ./ms-inventario
    container_name: ms-inventario
    ports:
      - "5004:5004"
    restart: always

  # ðŸ”´ Orquestador (coordinador de la Saga)
  orquestador:
    build: ./orquestador
    container_name: orquestador
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - ms-catalogo
      - ms-compras
      - ms-pagos
      - ms-inventario