version: "3.9"

services:

  ms-catalogo:
    build: ./ms-catalogo
    image: ms-catalogo-img
    container_name: ms-catalogo
    ports:
      - "5001:5001"

  ms-pagos:
    build: ./ms-pagos 
    image: ms-pagos-img
    container_name: ms-pagos
    ports:
      - "5002:5002"

  ms-inventario:
    build: ./ms-inventario
    image: ms-inventario-img
    container_name: ms-inventario
    ports:
      - "5003:5003"

  ms-compras:
    build: ./ms-compras
    image: ms-compras-img
    container_name: ms-compras
    ports:
      - "8080:8080"   # Spring Boot usa 8080 por defecto

  ms-orquestador:
    build: ./ms-orquestador
    image: ms-orquestador-img
    container_name: ms-orquestador
    ports:
      - "5010:5010"
    depends_on:
      - ms-catalogo
      - ms-pagos
      - ms-inventario
      - ms-compras
